### ISSUE TITLE
Progress 1

### ISSUE THREAD

**Issue by thomsaja** [alfianLyn/Responsi-2-PPD2#2]
Buat Main Program Awal

**Comment by alfianrhe** [comment]
1. Interface by Thomas, just a simple interface.
2. Check Java to MySQL connection.
3. Maybe isn't a made class by class is more implement to function

**Comment by thomsaja** [comment]
1. Interface untuk pegawai

**Comment by alfianrhe** [comment]
Fixing up some features...
Change log :

- Separated Admin and Owner features

- Just fixing some cases
